[package]
name = "generator"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
chrono-tz = "0.10.4"
markdown = "1.0.0"
mdast_util_to_markdown = "0.0.2"
rss = { version = "2.0.12", features = ["validation"] }
saphyr = "0.0.6"
